"""
Django settings for busmodel project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
import tempfile
from pathlib import Path
import environ

# Only uncomment when used as external dependency
# from django.conf.global_settings import *

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'ebustoolbox',
]

MIDDLEWARE = [
]

UPLOAD_PATH = tempfile.gettempdir()

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

assert os.environ['DATABASE_URL'] is not None, "DATABASE_URL environment variable must be set"
DATABASES = {'default': environ.Env().db('DATABASE_URL')}


#CELERY_BROKER_URL = None
CELERY_USE = False

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True
